language: c

dist: trusty
sudo: required

# https://docs.travis-ci.com/user/languages/c/
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-8
#env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install: 
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-get -y update
  - sudo apt-get install -y build-essential software-properties-common
  - sudo apt-get install -y gcc-snapshot
  - sudo apt-get install -y gcc-8 g++-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - sudo update-alternatives --config gcc
  - sudo gcc -v
  - sudo apt-get install -y cmake golang

script: sudo git clone --depth=1 --branch=master https://github.com/Minaminx/BoringSSL.git boringssl && sudo cd boringssl && sudo export CFLAGS="-Wno-error" && sudo mkdir build && sudo cd build && sudo cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_SMALL=1 ../ && sudo make && sudo cd .. && sudo mkdir -p .openssl/lib && sudo cd .openssl && sudo ln -s ../include . && sudo cd .. && sudo cp build/crypto/libcrypto.a build/ssl/libssl.a .openssl/lib && sudo cd ..
