language: c

sudo: required
dist: trusty

before_install: 
  - sudo echo -e "\ndeb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main\ndeb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty main\ndeb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main\ndeb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main\ndeb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main\ndeb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main\ndeb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y build-essential clang cmake ccache golang

script: 
  - git clone --depth=1 --branch=master https://github.com/Minaminx/BoringSSL.git boringssl
  - cd boringssl
  - export CFLAGS="-Wno-error"
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_SMALL=1 ../
  - make
  - cd ..
  - mkdir -p .openssl/lib && cd .openssl && ln -s ../include .
  - cd ..
  - cp build/crypto/libcrypto.a build/ssl/libssl.a .openssl/lib
  - cd ..